import { Animal, Vertebrae, ColorScheme, Pattern} from '../types'
export const mockAnimals: Animal[] = [
    {
	name: 'Clownfish',
	group: 'Fish',
	colorScheme: {color: ['orange', 'black', 'white'], pattern: ['striped']},
	location: ['water'],
	attribute: ['scale', 'fins', 'gills'],
},
{
	name: 'Electric Eel',
	group: 'Fish',
	colorScheme: {color: ['mixed', 'black', 'gold'], pattern: ['striped','solid']},
	location: ['water'],
	attribute: ['singular fin', 'gills'], 
},
{
	name: 'Blue Marlin',
	group: 'Fish',
	colorScheme: {color: ['stripped', 'split', 'blue', 'black', 'silver'], pattern: ['striped']},
	location: ['water'],
	attribute: ['fins', 'gills', 'spear-shaped jaw', 'scale'], 

},
{
    name: 'Great White Shark',
	group: 'Fish',
	colorScheme: {color: ['split', 'black', 'white', 'gray'], pattern: ['striped']},
	location: ['water'],
	attribute: ['fins', 'gills', 'big teeth', 'blood thirsty'], 
},
{
	name: 'Anglerfish',
	group: 'Fish',
	colorScheme: {color: ['orange', 'black'], pattern: ['transparent', 'solid']},
	location: ['water'],
	attribute: ['fins', 'gills', 'big teeth', 'huge mouth'], 
},
{
	name: 'Crocodile',
	colorScheme: {color: ['brown', 'black'], pattern: ['solid']},
	group: 'Reptile',
	location: ['water', 'land'],
	attribute: ['legs', 'scale', 'armor', 'tail'], 
},
{
	name: 'Chameleon',
	colorScheme: {color: ['mixed', 'green', 'black'], pattern: ['transparent', 'solid', 'striped', 'dotted', 'camouflage', 'split']},
	group: 'Reptile',
	location: ['land'],
	attribute: ['tail', 'long tongue', 'big eyes', 'scale', 'camouflage'], 
},

{
	name: 'KomodoDragon',
	colorScheme: {color: ['brown', 'black'], pattern: ['solid']},
	group: 'Reptile',
	location: ['water', 'land'],
	attribute: ['legs', 'poison', 'huge mouth', 'tail'], 
},
{
	name: 'Reptile',
	colorScheme: {color: ['black', 'brown'], pattern: ['striped', 'solid']},
	group: 'Reptile',
	location: ['land'],
	attribute: ['scale', 'face shield', 'poison', 'fangs'], 
},
{
	name: 'Nefarian',
	colorScheme: {color: ['black', 'red'], pattern: ['split', 'solid']},
	group: 'Reptile',
	location: ['land', 'air'],
	attribute: ['scale', 'fire breath', 'wings', 'huge mouth', 'fangs', 'tail', 'shapeshifter'], 
},
{
	name: 'Cardinal',
	colorScheme: {color: ['red'], pattern: ['solid']},
	group: 'Bird',
	location: ['land', 'air'],
	attribute: ['crested head', 'vibrant plumage', 'feathers'],
},
{
	name: 'Blue Jay',
	colorScheme: {color: ['blue', 'white', 'black'], pattern: ['solid', 'split']},
	group: 'Bird',
	location: ['land', 'air'],
	attribute: ['distinctive crest', 'bold colors', 'feathers'],
},
{
	name: 'Bald Eagle',
	colorScheme: {color: ['brown', 'white'], pattern: ['solid', 'split']},
	group: 'Bird',
	location: ['land', 'air'],
	attribute: ['white head', 'impressive wingspan', 'beak', 'feathers', 'talons'],
},
{
	name: 'Peacock',
	colorScheme: {color: ['blue', 'green', 'brown'], pattern: ['split', 'solid']},
	group: 'Bird',
	location: ['land'],
	attribute: ['vibrant tail feathers', 'elaborate courtship display', 'feathers', 'tail fan', 'mohawk'],
},
{
	name: 'Duck',
	colorScheme: {color: ['white'], pattern: ['solid']},
	group: 'Bird',
	location: ['land', 'air', 'water'],
	attribute: ['swim', 'webbed feet', 'wings', 'feathers']
},
{
	name: 'Lion',
	colorScheme: {color: ['golden', 'brown'], pattern: ['solid']},
	group: 'Mammal',
	location: ['land'],
	attribute: ['mane', 'roar', 'sharp claws'],
},
{
	name: 'Dolphin',
	colorScheme: {color: ['gray', 'blue'], pattern: ['solid', 'split']},
	group: 'Mammal',
	location: ['water'],
	attribute: ['streamlined body', 'intelligence', 'sonar communication', 'fins'],
},
{
	name: 'Polar Bear',
	colorScheme: {color: ['white'], pattern: ['solid']},
	group: 'Mammal',
	location: ['land', 'water'],
	attribute: ['thick fur', 'large paws', 'excellent swimmers'],
},
{
	name: 'Chimpanzee',
	colorScheme: {color: ['black', 'brown'], pattern: ['solid']},
	group: 'Mammal',
	location: ['land'],
	attribute: ['highly intelligent', 'tool usage', 'complex social behavior'],
},
{
	name: 'Kangaroo',
	colorScheme: {color: ['brown', 'gray'], pattern: ['solid']},
	group: 'Mammal',
	location: ['land'],
	attribute: ['powerful hind legs', 'pouch for carrying young', 'boxing'],
},{
	name: 'Red-eyed Tree Frog',
	colorScheme: {color: ['green', 'blue', 'red'], pattern: ['spotted']},
	group: 'Amphibian',
	location: ['land'],
	attribute: ['large red eyes', 'sticky toe pads', 'nocturnal'],
},
{
	name: 'Axolotl',
	colorScheme: {color: ['pink', 'white', 'gray'], pattern: ['spotted']},
	group: 'Amphibian',
	location: ['water'],
	attribute: ['external gills', 'regenerative abilities'],
},
{
	name: 'Poison Dart Frog',
	colorScheme: {color: ['brightly colored'], pattern: ['spotted']},
	group: 'Amphibian',
	location: ['land'],
	attribute: ['toxic skin secretions', 'small size'],
},
{
	name: 'Fire-bellied Toad',
	colorScheme: {color: ['black', 'green', 'orange'], pattern: ['spotted']},
	group: 'Amphibian',
	location: ['land', 'water'],
	attribute: ['brightly colored belly', 'toxic skin'],
},
{
	name: 'American Bullfrog',
	colorScheme: {color: ['green', 'brown'], pattern: ['solid']},
	group: 'Amphibian',
	location: ['water', 'land'],
	attribute: ['powerful hind legs', 'loud croaking'],
},
]

